PHONE_DISPLAY = "909-609-6685"
PHONE_HREF = "tel:+1" + PHONE_DISPLAY.replace("-", "")
FIRM_NAME = "The Berhe Law Firm, APC"
FIRM_PUBLIC_STATEMENT = "The Berhe Law Firm, APC is responsible for this website."
DISCLAIMER = (
    "Attorney advertising. General information only; not legal advice. A form, call, email, "
    "text, or public checklist request does not create an attorney-client relationship. "
    "Representation begins only after conflicts review and a signed written agreement. "
    "Deadlines vary. Do not send privileged, highly sensitive, or urgent information through "
    "public forms. No guarantee of outcome."
)

PRACTICES = [
    {
        "slug": "personal-injury-wrongful-death",
        "name": "Personal Injury and Wrongful Death",
        "title": f"California Personal Injury Lawyer | {FIRM_NAME}",
        "description": f"Hurt in a California crash, fall, or preventable death? {FIRM_NAME} reviews liability, medical proof, coverage, and deadlines free. Call 909-609-6685.",
        "h1": "Serious injury or wrongful death deserves more than a quick intake script.",
        "lead": "The first review connects responsibility, medical proof, life impact, available coverage, and any preservation or deadline issue.",
        "card": "A collision, a fall, an unsafe property, or a preventable death has changed your health, your income, and your family's plans. The other side's insurer started building its version of the story on day one.",
        "stakes": [
            "Medical bills and lost income arrive before any claim is resolved.",
            "Scene conditions, vehicle damage, and nearby video can change or disappear within days.",
            "An early recorded statement or signed release can shape the rest of the claim.",
        ],
        "fit": ["A person or organization may be legally responsible", "Injury, treatment, death, or life impact is documented", "Insurance or another recovery source may exist"],
        "evidence": ["Incident reports, scene photos, video, and witness details", "Medical records, bills, work restrictions, and a treatment timeline", "Insurance letters, claim numbers, damaged-property records, and preservation notices"],
        "evaluation": ["Causation between the event and the harm", "Past and future medical or life-impact evidence", "Coverage, collectability, comparative fault, and litigation leverage"],
        "faqs": [
            ("How long do I have to bring a California injury claim?", "Deadlines vary by claim type, by who is responsible, and by the forum involved. Claims involving public entities can carry separate and much shorter notice steps. This page does not calculate your deadline. Call promptly so timing can be reviewed against your facts."),
            ("Should I give the other insurer a recorded statement?", "You are generally not required to give a recorded statement to another party's insurer, and what you say can be used later. Consider getting the request reviewed first. Write down who called, when, and what they asked."),
            ("What if I was partly at fault?", "Shared responsibility does not automatically end a California claim, but it can affect what is recoverable. Bring the facts you have, including the parts you are unsure about, so fault can be reviewed honestly rather than assumed."),
        ],
        "related": [("What to prepare before a case review", "/resources/prepare-for-case-review/"), ("First steps after a California crash", "/resources/after-a-collision-first-steps/"), ("Catastrophic injury review", "/practice-areas/catastrophic-injury/")],
        "resource": "/resources/prepare-for-case-review/",
    },
    {
        "slug": "employment-workplace-claims",
        "name": "Employment and Workplace Claims",
        "title": f"California Employment Lawyer | {FIRM_NAME}",
        "description": f"Fired, demoted, or retaliated against in California? {FIRM_NAME} reviews the timeline, documents, and filing steps free. Call 909-609-6685 to start.",
        "h1": "Workplace claims need a clean timeline, documents, and deadline review.",
        "lead": "A useful employment screen starts with what happened, when it happened, who knew, what was reported, and what changed afterward.",
        "card": "You were fired, demoted, cut back, or pushed out after you raised a problem. The paycheck stopped, and the proof is sitting in an account you may lose access to.",
        "stakes": [
            "Access to work email, chat history, schedules, and pay records can end on the last day.",
            "Some workplace claims require an administrative step before a lawsuit is possible.",
            "Severance and separation paperwork can ask you to give up claims you have not reviewed yet.",
        ],
        "fit": ["A termination, discipline, pay issue, retaliation, discrimination, or harassment concern is supported by specific facts", "The employer and relevant decision-makers can be identified", "The chronology and resulting harm can be documented"],
        "evidence": ["Offer letters, policies, reviews, schedules, pay records, and personnel documents", "Emails, texts, complaints, notices, and agency correspondence", "A date-by-date chronology of reports, responses, and adverse actions"],
        "evaluation": ["Protected activity or status and the employer's stated reasons", "Administrative or filing deadlines that may apply", "Lost compensation, other damages, proof quality, and practical leverage"],
        "faqs": [
            ("I was told my job was eliminated. Is that the end of it?", "A stated business reason is one part of the review, not the whole review. What matters is the full chronology: what you reported or requested, who knew, what changed afterward, and whether the stated reason matches the records."),
            ("Do I have to file with an agency before I sue?", "Certain workplace claims involve an administrative process before a lawsuit, and those steps carry their own timing. Which path applies depends on the claim and the employer. Bring your notices and correspondence so the sequence can be reviewed."),
            ("Should I sign a severance agreement?", "A severance agreement usually asks you to release claims. Once signed, options can narrow. Keep the unsigned document, note any deadline printed on it, and get it reviewed before you decide."),
        ],
        "related": [("How to document a workplace problem", "/resources/workplace-documentation/"), ("Deadlines and early case review", "/resources/deadlines-and-early-review/"), ("Civil rights and government accountability", "/practice-areas/civil-rights-government-accountability/")],
        "resource": "/resources/deadlines-and-early-review/",
    },
    {
        "slug": "civil-rights-government-accountability",
        "name": "Civil Rights and Government Accountability",
        "title": f"California Civil Rights Lawyer | {FIRM_NAME}",
        "description": f"Harmed by a government actor or public entity in California? {FIRM_NAME} reviews video, records, notice steps, and deadlines free. Call 909-609-6685.",
        "h1": "Civil rights and government-accountability matters are deadline-sensitive and evidence-driven.",
        "lead": "Early review can matter when a public entity, government actor, video record, or special notice process may be involved.",
        "card": "A public agency or a government actor caused harm, and the records that would prove it are held by the same institution you are questioning.",
        "stakes": [
            "Claims involving public entities can carry separate notice steps that run early.",
            "Body camera, dispatch, jail, and facility video is often kept only for a set retention period.",
            "Records requests take time, and the request history itself becomes part of the record.",
        ],
        "fit": ["A government actor, agency, contractor, or rights-based harm can be identified", "The event and resulting harm are supported by specific facts", "There may be a viable forum, defendant, and recovery path"],
        "evidence": ["Video, audio, photographs, dispatch or incident information, and witness details", "Agency notices, reports, citations, correspondence, and medical records", "Dates, locations, badge or vehicle details, and records-request history"],
        "evaluation": ["Government-claim and other timing issues without assuming one universal deadline", "Preservation and access to video or agency records", "Causation, damages, immunity or defense issues, and forum"],
        "faqs": [
            ("Is a claim against a city or county different from a normal lawsuit?", "Matters involving public entities can involve additional procedural steps and separate timing that do not apply to private defendants. The specific steps depend on the entity and the claim, so the sequence should be reviewed early rather than assumed."),
            ("How do I keep agency video from being erased?", "Agencies keep recordings for limited retention periods that vary by department and system. Write down the date, time, location, and any incident or report number, and raise preservation as early as possible so a request can be evaluated."),
            ("Can I bring a claim if no one was arrested or charged?", "Charging decisions are made by prosecutors and are a separate question from a civil claim. What matters for a civil review is the conduct, the harm, the available proof, and the applicable procedure."),
        ],
        "related": [("Deadlines and early case review", "/resources/deadlines-and-early-review/"), ("What to prepare before a case review", "/resources/prepare-for-case-review/"), ("Personal injury and wrongful death", "/practice-areas/personal-injury-wrongful-death/")],
        "resource": "/resources/deadlines-and-early-review/",
    },
    {
        "slug": "consumer-protection-lemon-law",
        "name": "Consumer Protection and Lemon Law",
        "title": f"California Lemon Law and Consumer Lawyer | {FIRM_NAME}",
        "description": f"Defective vehicle, warranty runaround, or deceptive sale in California? {FIRM_NAME} reviews repair history, contracts, and loss free. Call 909-609-6685.",
        "h1": "Consumer cases usually turn on documents, dates, and a defendant that can be held accountable.",
        "lead": "The first review focuses on the transaction, what was promised, repair or complaint history, notices, measurable loss, and the responsible business.",
        "card": "A vehicle, product, lender, or seller failed, and the company keeps routing you back into the same repair loop or the same phone queue.",
        "stakes": [
            "Repair orders and service records are the backbone of a warranty file, and copies are easy to lose.",
            "Written promises made at the counter often differ from the signed contract.",
            "Continuing to pay, trade in, or sell the item can change what a review is able to test.",
        ],
        "fit": ["A purchase, lease, warranty, repair, financing, or deceptive-practice issue is documented", "The responsible seller, manufacturer, lender, or business can be identified", "The loss and requested resolution can be explained"],
        "evidence": ["Contracts, advertisements, disclosures, warranties, and finance records", "Repair orders, complaint history, notices, emails, and call notes", "Payment records, loss calculations, and the business's written response"],
        "evaluation": ["Statutory or contract framework and available fee path", "Notice, repair opportunity, reliance, and causation", "Damages, defendant solvency, collectability, and resolution posture"],
        "faqs": [
            ("What records matter most in a defective vehicle claim?", "Every repair order, including the ones that say no problem was found, plus the purchase or lease contract, the warranty booklet, finance documents, and a list of the dates the item was out of service. Ask the service department for printed copies each visit."),
            ("The dealer says the problem cannot be reproduced. Does that end the claim?", "Not automatically. A repair attempt that resolves nothing is still a documented attempt. Keep your own log of dates, symptoms, mileage, and who you spoke with, and photograph or record the symptom when it appears if it is safe to do so."),
            ("Do I have to keep making payments?", "Stopping payment can create separate financial and credit consequences that are not part of the underlying dispute. Do not treat a website as advice on your specific contract. Bring the finance documents so the practical options can be discussed."),
        ],
        "related": [("Talking to an insurance or claims adjuster", "/resources/insurance-claim-communication/"), ("What to prepare before a case review", "/resources/prepare-for-case-review/"), ("Insurance bad faith review", "/practice-areas/insurance-bad-faith/")],
        "resource": "/resources/prepare-for-case-review/",
    },
    {
        "slug": "insurance-bad-faith",
        "name": "Insurance Bad Faith",
        "title": f"California Insurance Bad Faith Lawyer | {FIRM_NAME}",
        "description": f"Claim denied, delayed, or underpaid in California? {FIRM_NAME} reviews the policy, claim file, and insurer communications free. Call 909-609-6685.",
        "h1": "When an insurer delays, denies, or underpays, the file needs policy-first review.",
        "lead": "The policy, complete claim chronology, insurer communications, underlying loss, and resulting harm anchor the first screen.",
        "card": "You paid the premiums for years. Now the claim is delayed, underpaid, or denied, the repairs are unfinished, and the bills keep arriving.",
        "stakes": [
            "Policies contain their own notice, proof of loss, and cooperation steps with their own timing.",
            "A denial letter states reasons that shape the entire dispute, so the wording matters.",
            "Repairing, discarding, or replacing damaged property can remove the proof of the loss.",
        ],
        "fit": ["A policy and covered loss or defense request can be identified", "The insurer delayed, denied, underpaid, or took another disputed position", "The claim history and resulting harm are documented"],
        "evidence": ["Policy, declarations, endorsements, claim number, and proof of loss", "Denial, reservation-of-rights, delay, estimate, and payment letters", "A chronology of calls, submissions, inspections, requests, and responses"],
        "evaluation": ["Policy language and the insurer's stated coverage position", "Reasonableness of investigation, communication, delay, or valuation", "Underlying loss, damages beyond policy benefits, and litigation posture"],
        "faqs": [
            ("What should I ask my insurer to put in writing?", "Ask for the claim number, the adjuster and supervisor contact information, the specific policy provisions being relied on, the reason for any denial or reduction, and a copy of the complete policy including endorsements. Keep every response."),
            ("Is a low estimate the same as bad faith?", "A disagreement about value is not automatically a bad faith claim. The review looks at the policy language, the investigation, the communications, the timing, and whether the position taken was supported. Bring the estimates and letters so the conduct can be examined."),
            ("What if the insurer is defending me but sent a reservation of rights?", "A reservation of rights letter tells you the insurer is defending while reserving positions on coverage. Keep it. That letter, the policy, and the correspondence are central documents in any later coverage dispute."),
        ],
        "related": [("Talking to an insurance or claims adjuster", "/resources/insurance-claim-communication/"), ("What to prepare before a case review", "/resources/prepare-for-case-review/"), ("Consumer protection and Lemon Law", "/practice-areas/consumer-protection-lemon-law/")],
        "resource": "/resources/prepare-for-case-review/",
    },
    {
        "slug": "catastrophic-injury",
        "name": "Catastrophic Injury",
        "title": f"California Catastrophic Injury Lawyer | {FIRM_NAME}",
        "description": f"Life-changing injury in California? {FIRM_NAME} reviews liability, future care needs, coverage layers, and evidence preservation free. Call 909-609-6685.",
        "h1": "Catastrophic injury cases require early investigation and a real damages strategy.",
        "lead": "Severe harm requires proof of responsibility and a disciplined record of medical needs, future care, work impact, family impact, and available recovery sources.",
        "card": "The injury changed what the next thirty years look like. Care, work, housing, and family roles all shifted at once, and decisions are being asked of you now.",
        "stakes": [
            "Future care, equipment, and home access needs have to be documented as they develop.",
            "Physical evidence such as a vehicle, machine, or product can be repaired or scrapped quickly.",
            "More than one insurance layer or responsible organization may exist, and each has its own process.",
        ],
        "fit": ["The injury creates major, lasting, or complex medical and life consequences", "A responsible person or organization and liability theory can be investigated", "Coverage, assets, or another realistic recovery source may exist"],
        "evidence": ["Acute-care, specialist, rehabilitation, imaging, and prognosis records", "Work history, care needs, home changes, family observations, and daily-impact notes", "Incident proof, product or vehicle information, insurance layers, and witness details"],
        "evaluation": ["Medical causation, severity, prognosis, and future-care needs", "Life-care, vocational, earnings, household, and noneconomic impact", "Fault, defendant profile, insurance layers, expert needs, and litigation leverage"],
        "faqs": [
            ("The person injured cannot manage the claim. Who can call?", "A spouse, parent, adult child, or another person close to the situation can describe what happened and what is needed. Authority to act for an injured adult is a separate legal question that is addressed during the review."),
            ("What should the family be recording right now?", "Keep a simple dated journal of care hours, missed work, equipment purchased, home modifications, appointments, and daily limitations. Contemporaneous notes made now are more useful than a reconstruction attempted months later."),
            ("Why does a catastrophic case need investigation so early?", "Vehicles get repaired, machines get returned to service, products get discarded, and scenes get restored. Once the physical evidence is gone, the case depends on whatever record already exists."),
        ],
        "related": [("First steps after a California crash", "/resources/after-a-collision-first-steps/"), ("Commercial-vehicle evidence checklist", "/resources/commercial-vehicle-evidence-checklist/"), ("Personal injury and wrongful death", "/practice-areas/personal-injury-wrongful-death/")],
        "resource": "/resources/prepare-for-case-review/",
    },
    {
        "slug": "select-civil-litigation",
        "name": "Select Civil Litigation",
        "title": f"California Civil Litigation Lawyer | {FIRM_NAME}",
        "description": f"Serious fraud, contract, fiduciary, or business tort dispute in California? {FIRM_NAME} reviews proof, damages, and economics free. Call 909-609-6685.",
        "h1": "Select civil litigation is accepted only when the facts and economics justify the work.",
        "lead": "The first screen tests documented wrongdoing, provable damages, timing, forum, collectability, and whether the fee structure fits the work required.",
        "card": "A business, a partner, or a professional caused serious documented loss, and the other side already has counsel drafting its version of events.",
        "stakes": [
            "Contracts often contain notice, venue, or dispute-resolution steps that control what happens first.",
            "Accounting records, shared drives, and message histories can be closed off once a dispute becomes open.",
            "Litigation economics matter, because a claim that cannot be collected is a claim that costs more than it returns.",
        ],
        "fit": ["The dispute involves serious, documented wrongdoing or breach", "Damages are measurable and proportionate to the likely litigation burden", "The defendant and a realistic recovery source can be identified"],
        "evidence": ["Contracts, communications, transaction records, notices, and governing documents", "A chronology of decisions, representations, payments, and resulting loss", "Existing pleadings, demands, responses, deadline information, and party list"],
        "evaluation": ["Legal and factual merits, defenses, forum, and procedural posture", "Provable economics, expert needs, costs, and fee-structure fit", "Defendant solvency, collectability, settlement posture, and litigation leverage"],
        "faqs": [
            ("What makes a civil dispute worth litigating?", "Documented wrongdoing, damages that can be proven with records rather than estimates, a defendant who can actually satisfy a judgment, and a cost structure that fits the work the case will require."),
            ("I already have a lawsuit on file. Can the firm still look at it?", "A pending matter can be reviewed for co-counsel or referral. Send the general posture, the court, the deadlines, and the parties for conflicts. Do not send privileged strategy material in a public form."),
            ("What should I gather before the first conversation?", "The controlling contract or governing documents, the communications that show what was promised and what happened, the transaction or accounting records that quantify the loss, and a list of every party involved."),
        ],
        "related": [("What to prepare before a case review", "/resources/prepare-for-case-review/"), ("Referrals and co-counsel", "/referrals-co-counsel/"), ("Consumer protection and Lemon Law", "/practice-areas/consumer-protection-lemon-law/")],
        "resource": "/resources/prepare-for-case-review/",
    },
]

# Editorial resource library. Each guide renders a full public page and is the
# single source for the resource hub, ROUTES, sitemap, and internal linking.
RESOURCE_GUIDES = [
    {
        "slug": "prepare-for-case-review",
        "name": "What to prepare before a case review",
        "title": f"What to Prepare Before a Case Review | {FIRM_NAME}",
        "description": "A conflict-safe checklist for a California case review: the parties, dates, documents, harm, and questions to organize before you call. General information only.",
        "h1": "What to prepare before a case review.",
        "lead": "Organize the facts that let an attorney see timing, responsibility, harm, evidence, and a practical recovery route.",
        "summary": "Use this before your first call so the conversation starts with your facts instead of a form.",
        "intro": [
            "Most first calls stall for the same reason: the story is clear in your head and scattered everywhere else. Organizing six things first turns a vague conversation into a review that can actually reach a decision.",
            "None of this requires a complete file. It requires the parties, the dates, the harm, and the documents you already have.",
        ],
        "sections": [
            ("basic-facts", "The six facts to organize first", "A useful first request is specific and short.", [
                "Who is involved, including anyone who may be on the other side",
                "What happened, where it happened, and on what dates",
                "What changed afterward, and what harm or loss resulted",
                "What documents, witnesses, photographs, video, or records exist",
                "What deadlines, notices, hearings, or agency dates you already know about",
                "What question or outcome you want reviewed",
            ]),
            ("chronology", "Build a chronology someone else can follow", "A date list gives the reviewer a practical starting point.", [
                "Start at the first relevant event, not at the moment things went wrong",
                "Give each entry a date, a short description, and the source that proves it",
                "Mark the entries you can prove with a document and the ones that rest on memory",
                "Note every date someone told you to respond by, and where that instruction came from",
                "Keep the chronology in one file and update it instead of starting over",
            ]),
            ("documents", "Gather the documents that anchor the story", "Originals matter. Keep them intact and work from copies.", [
                "Contracts, policies, notices, letters, and anything you signed",
                "Photographs and video with the original file and its date information preserved",
                "Medical, repair, payroll, or accounting records that quantify the harm",
                "Messages and email threads exported or screenshotted in full, not cropped",
                "Any correspondence from an insurer, employer, agency, or opposing company",
            ]),
            ("hold-back", "What not to send through a public form", "Keep sensitive material for an approved follow-up channel.", [
                "Do not send a full records dump or an entire medical file",
                "Do not send passwords, credentials, Social Security numbers, or financial account details",
                "Do not send material from another lawyer's file without reviewing how it should be handled",
                "Do not rely on a public form for anything urgent; call instead",
            ]),
        ],
        "expect": [
            ("A conflicts and parties check", "The first question is who is involved on every side, because that determines whether a closer review is even possible."),
            ("A timing screen", "Known dates, notices, and hearings are identified early, since timing can change the order of everything else."),
            ("A fit and proof discussion", "Responsibility, available proof, documented harm, and a practical recovery source are reviewed together."),
            ("A clear next step", "The matter may move to an engagement discussion, a request for more information, a referral, or a decline. No outcome and no response time is promised."),
        ],
        "preserve": [
            "The original photographs and video files, not just copies sent through messaging apps",
            "Every letter and envelope, including the postmark",
            "Damaged property, clothing, devices, or parts in the condition they are in now",
            "Account access, exports, or printouts for anything you might lose access to",
        ],
        "faqs": [
            ("How much detail should the first message include?", "Enough to identify the parties, the dates, what happened, and the harm. A short, organized summary is more useful than a long narrative, and a public form is not the place for sensitive records."),
            ("What if I do not have all the documents yet?", "Missing documents are normal at this stage. List what exists, where it is, and what you cannot access, so the gaps are part of the review instead of a surprise later."),
            ("Does sending this information make the firm my lawyer?", "No. Contact does not create an attorney-client relationship. Representation begins only after conflicts review and a signed written agreement."),
        ],
        "related": [
            ("Deadlines and early case review", "/resources/deadlines-and-early-review/"),
            ("How the case review process works", "/case-review-process/"),
            ("Find the practice area closest to your facts", "/practice-areas/"),
        ],
    },
    {
        "slug": "commercial-vehicle-evidence-checklist",
        "name": "Commercial-vehicle accident evidence checklist",
        "title": f"Truck and Rideshare Evidence Checklist | {FIRM_NAME}",
        "description": "Evidence checklist for California truck, fleet, delivery, and rideshare crashes: scene proof, carrier records, telematics, video retention, and preservation steps.",
        "h1": "Commercial-vehicle accident evidence checklist.",
        "lead": "Commercial vehicle evidence is spread across a driver, a carrier, a platform, an owner, a maintenance provider, insurers, devices, and nearby cameras.",
        "summary": "Records that may be important in a commercial-vehicle matter are often held by the company, not by you.",
        "intro": [
            "A crash involving a truck, a delivery van, a company vehicle, or a rideshare driver is rarely a two-party event. Behind the driver there can be a carrier, a broker, a vehicle owner, a maintenance vendor, a staffing company, and more than one insurer.",
            "Much of the proof is electronic, held by those companies, and subject to retention schedules that keep it for a limited time. What you capture in the first days can affect what is still available later.",
        ],
        "sections": [
            ("scene", "Crash scene and vehicle proof", "Preserve what identifies the event and every organization connected to it.", [
                "Photographs of the scene, both vehicles, cargo, road conditions, skid marks, and debris",
                "License plates, USDOT and MC numbers, company markings, trailer numbers, and placards",
                "Driver name, license, employer, and the app or trip details if a platform was involved",
                "The report number, the responding agency, and the names of any responding units",
                "Witness names and phone numbers, plus nearby businesses that may have cameras",
            ]),
            ("company", "Carrier, platform, and vehicle records", "These are the records you cannot recreate later.", [
                "Dispatch, trip, and load documents connected to the run",
                "Hiring, training, qualification, and supervision records for the driver",
                "Maintenance, inspection, repair, brake, and tire service history for the vehicle",
                "Leasing, ownership, permission, and registration documents",
                "Insurance information for the driver, the vehicle owner, and the company",
            ]),
            ("electronic", "Electronic data with short retention windows", "Ask early. Many of these systems overwrite on a schedule.", [
                "Electronic logging device and hours-of-service data",
                "Telematics, GPS, and fleet-management records",
                "Event data recorder information from the vehicles involved",
                "Dash camera footage, in-cab video, and rideshare app trip data",
                "Traffic, transit, business, and residential camera video near the location",
            ]),
            ("medical", "Treatment, work impact, and communications", "Build a date-indexed record without altering originals.", [
                "Every treatment date, provider, restriction, and follow-up instruction",
                "Bills, explanations of benefits, and out-of-pocket costs",
                "Missed work, reduced hours, and any written employer communication",
                "All insurance letters, requests for statements, and requests to sign anything",
                "Known government, claim, insurer, or court dates",
            ]),
        ],
        "expect": [
            ("An early preservation discussion", "Which records may be time-sensitive, and which organizations may hold them, is one of the first things reviewed."),
            ("A party map", "Driver, employer, owner, broker, platform, maintenance vendor, and insurers are identified as separate potential sources of responsibility and coverage."),
            ("A proof and damages review", "Scene proof, medical documentation, work impact, and vehicle evidence are reviewed together rather than one at a time."),
            ("A next-step decision", "The firm may accept, refer, co-counsel, or decline after conflicts and fit review. Contact alone is not representation."),
        ],
        "preserve": [
            "The vehicle itself, before it is repaired, sold, or scrapped",
            "Damaged safety equipment, child seats, helmets, devices, and clothing",
            "Original photo and video files with their date information intact",
            "Every insurer letter, estimate, and request for a recorded statement",
        ],
        "faqs": [
            ("How quickly can commercial-vehicle records disappear?", "Retention periods vary by company and by system, and some electronic records are kept for a short window before being overwritten. That is why preservation is raised at the very beginning rather than after a claim is filed."),
            ("The other driver said the company would handle it. Is that enough?", "A verbal assurance is not a record. Get the claim number, the company name, the adjuster contact, and any promise in writing, and keep documenting your own treatment and losses in the meantime."),
            ("Does a rideshare crash work the same way?", "The evidence map is similar, but trip status, app data, and the platform's own insurance structure add records that are held by the platform. Save the trip receipt, screenshots, and driver information immediately."),
        ],
        "related": [
            ("Commercial vehicle case review", "/landing/truck-fleet-rideshare-accident-california/"),
            ("First steps after a California crash", "/resources/after-a-collision-first-steps/"),
            ("Catastrophic injury review", "/practice-areas/catastrophic-injury/"),
        ],
    },
    {
        "slug": "deadlines-and-early-review",
        "name": "Deadlines and early case review",
        "title": f"California Legal Deadlines Guide | {FIRM_NAME}",
        "description": "Why California civil deadlines are not one number: notice steps, agency processes, insurance timing, and evidence that disappears. General information, not advice.",
        "h1": "Why early review can matter when deadlines are unclear.",
        "lead": "No general guide can calculate an individual deadline. Early organization helps counsel identify which dates and procedures need attention first.",
        "summary": "There is no single legal deadline. There are several, they depend on your facts, and some run early.",
        "intro": [
            "People often ask for one number. Civil matters do not work that way. The applicable timing can depend on the type of claim, who is responsible, whether a public entity is involved, whether an administrative step applies, and what a contract or policy requires.",
            "This guide does not calculate your deadline and cannot. It explains which categories of timing tend to matter so that the right questions get asked early, while options are still open.",
        ],
        "sections": [
            ("categories", "Categories of timing that come up", "Different facts can trigger different notices, agency steps, contract terms, or filing rules.", [
                "Claims involving public entities, government actors, or public employees",
                "Workplace complaints that may involve an administrative process before a lawsuit",
                "Insurance policy requirements such as notice, proof of loss, or cooperation steps",
                "Contract terms that set notice, cure, venue, or dispute-resolution steps",
                "Evidence that disappears on its own schedule, which is a practical deadline even when no law sets it",
            ]),
            ("evidence-clock", "The evidence clock runs separately", "Proof can expire long before any filing date.", [
                "Surveillance and body camera video kept only for a set retention period",
                "Vehicles, machines, and products that get repaired, returned, or scrapped",
                "App, telematics, and log data that is overwritten on a cycle",
                "Scenes that are cleaned, repaved, repainted, or rebuilt",
                "Witnesses who move, change jobs, or simply stop remembering details",
            ]),
            ("organize", "How to organize timing facts", "Create a record another person can verify.", [
                "Build a date list from the first relevant event through today",
                "Save dated notices, letters, envelopes, emails, texts, filings, and agency records",
                "List who contacted you, when, how, and what they asked for",
                "Flag anything you signed and every date someone told you to respond by",
                "Write down what you were told verbally, including who said it and when",
            ]),
            ("act", "What to do when a date may be close", "Treat an unclear deadline as an urgent one.", [
                "Call rather than relying on a public form, since a submission does not stop any deadline",
                "Say clearly at the start of the call that you believe a date may be close",
                "Keep pursuing your own protective options, including contacting another qualified attorney promptly",
                "Do not assume a phone call, an email, or a website submission preserves anything",
            ]),
        ],
        "expect": [
            ("Timing questions first", "The review starts with known dates, notices, and anything that suggests an approaching deadline."),
            ("No deadline calculation from a web page", "A specific date cannot be determined from general information. It depends on the claim, the parties, and the forum."),
            ("A preservation conversation", "What may disappear, and how soon, is treated as its own timeline."),
            ("A candid next step", "If the firm is not the right fit, that is said directly so you can keep pursuing other options without losing time."),
        ],
        "preserve": [
            "Every envelope, notice, and letter with its date",
            "Screenshots of portals, filings, or messages that may expire",
            "A written note of each verbal instruction and who gave it",
            "Copies of anything you already signed",
        ],
        "faqs": [
            ("Can you tell me my deadline over the phone?", "A specific date depends on the claim, the parties, the forum, and the facts, and it is not something a general information page or a first call can definitively resolve. Timing questions are reviewed with your documents."),
            ("Does contacting a law firm stop the clock?", "No. Contact does not pause, extend, or preserve any deadline, and it does not create an attorney-client relationship. If a date may be close, keep pursuing your own options promptly."),
            ("What if I think a deadline already passed?", "It is still worth raising promptly. Timing analysis can be more complicated than it first appears, and waiting longer does not improve the situation."),
        ],
        "related": [
            ("What to prepare before a case review", "/resources/prepare-for-case-review/"),
            ("How the case review process works", "/case-review-process/"),
            ("Civil rights and government accountability", "/practice-areas/civil-rights-government-accountability/"),
        ],
    },
    {
        "slug": "after-a-collision-first-steps",
        "name": "First steps after a California crash",
        "title": f"What to Do After a California Car Accident | {FIRM_NAME}",
        "description": "A practical checklist for the first hours, days, and weeks after a California crash: documentation, medical records, insurer calls, and evidence that disappears fast.",
        "h1": "What to do in the first days after a California crash.",
        "lead": "The first week often contains the earliest available record of what happened. Much of that information is practical to collect, and some of it can change quickly.",
        "summary": "Proof can change or disappear during the first week. Here is what to capture while it is available.",
        "intro": [
            "After a collision, two things happen at once. You are dealing with injuries, transportation, work, and family logistics, while the evidence that explains what happened begins to disappear.",
            "This guide is general information, not legal advice, and it does not tell you what your claim is worth or what deadline applies. It lists the practical steps that tend to preserve options.",
        ],
        "sections": [
            ("first-hours", "The first hours", "Safety and documentation, in that order.", [
                "Seek appropriate medical attention and give providers an accurate account of every symptom you notice",
                "Get the report number, the responding agency, and the badge or unit information",
                "Photograph both vehicles, the full scene, road conditions, signage, and the final resting positions",
                "Collect names, phone numbers, insurance details, and license plate numbers for everyone involved",
                "Ask witnesses for a phone number before they leave, because they are hard to find later",
            ]),
            ("first-days", "The first days", "Start the paper trail while details are still fresh.", [
                "Write down what happened in your own words, dated, before memory reshapes it",
                "Photograph visible injuries repeatedly as they develop and heal",
                "Keep every discharge instruction, prescription, referral, and follow-up appointment",
                "Note missed work, reduced duties, and any conversation with your employer about it",
                "Identify nearby businesses, homes, or intersections that may have had a camera pointed at the location",
            ]),
            ("insurers", "When the insurers call", "You can be cooperative and careful at the same time.", [
                "Write down who called, the company, the claim number, and what was requested",
                "Ask whether a recorded statement is required under any applicable policy or agreement before agreeing, especially when the request comes from another party's insurer",
                "Read anything before signing it, especially a release or a medical authorization",
                "Do not guess about injuries, speeds, distances, or fault; saying you do not know yet is accurate",
                "Keep every letter and email, including the ones that look routine",
            ]),
            ("weeks", "The following weeks", "Consistency is what makes the record credible.", [
                "Keep treatment instructions and records explaining any missed appointments or barriers to care",
                "Track mileage, out-of-pocket costs, childcare, and help you needed at home",
                "Before repair or sale, ask whether the vehicle's condition needs independent documentation and preserve clear photos of the damage",
                "Save repair estimates, total-loss valuations, and rental records",
                "Consider limiting public posts about the crash, injuries, or activities while the facts are being evaluated",
            ]),
        ],
        "expect": [
            ("A liability and coverage conversation", "Who may be responsible, and which insurance may apply, are reviewed together rather than separately."),
            ("A medical documentation review", "Treatment history, gaps in care, and restrictions are discussed because they carry the injury proof."),
            ("A preservation list", "Vehicle, video, scene, and device evidence that may disappear is identified early."),
            ("A next-step decision", "The firm may accept, refer, co-counsel, or decline after conflicts and fit review. No outcome is promised."),
        ],
        "preserve": [
            "The vehicle before it is repaired or sold, and the damaged parts if it is",
            "Original photo and video files with their date information",
            "Every insurer letter, estimate, authorization, and release request",
            "A dated log of symptoms, appointments, missed work, and out-of-pocket costs",
        ],
        "faqs": [
            ("I felt fine at the scene and sore the next day. Does that hurt my claim?", "Symptoms may be noticed or recorded later. What helps a review is an accurate medical history and a clear timeline rather than a guess about how the delay affects any particular claim."),
            ("Do I have to talk to the other driver's insurance company?", "Whether a response is required depends on who is asking and any applicable policy or agreement. You can record the claim number, the adjuster's contact information, and the request itself, then ask for review before giving a recorded statement if you are unsure."),
            ("What if the other driver was working at the time?", "That can change who is responsible and which insurance applies. Save the company name, vehicle markings, and any delivery or trip information, and see the commercial-vehicle evidence checklist."),
        ],
        "related": [
            ("Commercial-vehicle evidence checklist", "/resources/commercial-vehicle-evidence-checklist/"),
            ("Talking to an insurance or claims adjuster", "/resources/insurance-claim-communication/"),
            ("Personal injury and wrongful death review", "/practice-areas/personal-injury-wrongful-death/"),
        ],
    },
    {
        "slug": "insurance-claim-communication",
        "name": "Talking to an insurance or claims adjuster",
        "title": f"Insurance Adjuster Calls and Releases | {FIRM_NAME}",
        "description": "What to know before a recorded statement, a medical authorization, or a release: what to document, what to ask in writing, and what a denial letter should contain.",
        "h1": "What to know before you talk to a claims adjuster.",
        "lead": "Claim files are built out of documents and recorded words. Understanding what is being asked, and why, keeps a routine call from narrowing your options.",
        "summary": "Recorded statements, authorizations, and releases are documents with consequences. Read before you sign.",
        "intro": [
            "An adjuster's job is to investigate and value a claim for the company that employs them. That is a legitimate role, and it is not the same role as yours.",
            "This guide is general information, not legal advice about your policy or your claim. It explains what the common requests are, what they typically do, and what to record along the way.",
        ],
        "sections": [
            ("first-call", "The first call", "Two minutes of notes now saves weeks of reconstruction later.", [
                "Record the date, the caller, the company, the claim number, and the direct contact information",
                "Ask which policy and which insured the call relates to",
                "Ask what is being requested and by when, then write the answer down",
                "Give accurate identifying information and avoid speculating about fault, speed, or injuries",
                "Follow up important calls with a short email confirming what was discussed",
            ]),
            ("requests", "The three requests to slow down on", "Each can create a lasting record or affect the scope of a claim.", [
                "A recorded statement, which becomes a transcript that can be used later",
                "A blanket medical authorization, which can open records well beyond the incident",
                "A release, which may end or narrow the claims covered in exchange for the payment described",
                "Any deadline attached to those requests, in writing, with the date it was given",
            ]),
            ("writing", "What to ask for in writing", "A claim file you can read is a claim file you can question.", [
                "A complete copy of the policy, including declarations and endorsements",
                "The specific provisions the company is relying on for any denial or reduction",
                "The written reason for a delay, and what is still outstanding",
                "Copies of the estimates, inspection reports, or valuations being used",
                "Confirmation of what has been received and what remains missing",
            ]),
            ("denial", "If the claim is delayed, underpaid, or denied", "Keep the record intact and keep it moving.", [
                "Save the denial or reservation-of-rights letter exactly as received",
                "Write a dated chronology of every submission, call, inspection, and response",
                "Do not discard, repair over, or dispose of damaged property before it is documented",
                "Keep track of any policy duties or written deadlines while seeking advice about the dispute",
                "Get the letters reviewed rather than assuming the stated reason is the whole story",
            ]),
        ],
        "expect": [
            ("A policy-first review", "The policy language and the insurer's stated position are read together before anything else is assessed."),
            ("A chronology review", "Timing of submissions, inspections, and responses is often as important as the substance."),
            ("A documentation gap check", "What the company says is missing, and what you already sent, are compared directly."),
            ("A next-step decision", "The firm may accept, refer, co-counsel, or decline after conflicts and fit review. No result is promised."),
        ],
        "preserve": [
            "Every letter, email, estimate, and voicemail from the company",
            "Photographs of damaged property before repair, cleanup, or disposal",
            "Your own dated log of calls, including who said what",
            "Anything you were asked to sign, whether or not you signed it",
        ],
        "faqs": [
            ("Is a recorded statement required?", "Your own policy may include cooperation obligations, which is different from a request by another party's insurer. Before agreeing, ask what the statement is for, note the request in writing, and get it reviewed if you are unsure."),
            ("What does a release actually do?", "A release generally ends the claim it covers in exchange for the stated payment. Because it can close options permanently, it should be read completely and reviewed before signing, not after."),
            ("Why do they want my full medical history?", "A broad authorization can reach records unrelated to the incident. It is reasonable to ask for the scope, the time period, and the providers to be limited to what the claim actually concerns."),
        ],
        "related": [
            ("Insurance bad faith review", "/practice-areas/insurance-bad-faith/"),
            ("First steps after a California crash", "/resources/after-a-collision-first-steps/"),
            ("What to prepare before a case review", "/resources/prepare-for-case-review/"),
        ],
    },
    {
        "slug": "workplace-documentation",
        "name": "How to document a workplace problem",
        "title": f"California Workplace Documentation Guide | {FIRM_NAME}",
        "description": "Build a workplace record before access ends: chronology, written reports, pay and schedule records, and what to keep after a termination. General information only.",
        "h1": "How to document a workplace problem while you still have access.",
        "lead": "Employment matters are often evaluated through chronology and records. Many of those records live in systems your employer controls.",
        "summary": "Access may end on or before the last day. Organize records you are entitled to keep while they remain available.",
        "intro": [
            "A usable workplace chronology tracks what happened, when, who knew, what was reported, and what changed afterward.",
            "This guide is general information, not legal advice. It does not tell you whether to report, resign, or sign anything. It describes how to keep a record that can be reviewed if you decide to have it reviewed.",
        ],
        "sections": [
            ("chronology", "Keep a dated chronology", "Contemporaneous notes are more persuasive than later recollection.", [
                "Log the date, the people present, what was said, and what happened next",
                "Record it the same day when possible, and note when you are writing from memory",
                "Keep the log somewhere personal, not on a work device or a work account",
                "Note the business reason you were given for each decision, in the words used",
                "Track schedule, duty, pay, and treatment changes that follow a report or a request",
            ]),
            ("reporting", "Put reports in a form that leaves a trace", "Verbal reports are easy to dispute later.", [
                "Review any written reporting process in the handbook and keep a copy of the version you relied on",
                "Confirm verbal conversations with a short, factual written follow-up",
                "Keep copies of the complaint, the acknowledgment, and any investigation communication",
                "Note who you reported to, their role, and the date",
                "Save any response, including the absence of one, with its date",
            ]),
            ("records", "Collect the records you are entitled to keep", "Focus on your own employment records, not company confidential material.", [
                "Offer letter, job description, handbook, and any policies you were asked to sign",
                "Performance reviews, write-ups, awards, schedules, and time records",
                "Pay stubs, wage statements, commission or bonus plans, and expense records",
                "Leave, accommodation, or medical-related correspondence relating to you",
                "Your personnel file, requested through the process your employer provides",
            ]),
            ("separation", "If separation is coming or already happened", "Access usually ends the same day the job does.", [
                "Save personal copies of your own records before the last day, without taking confidential company material",
                "Keep the separation letter, final pay documents, and severance paperwork, note every signature deadline, and consider review before signing",
                "Note every deadline printed on separation documents",
                "Preserve messages, voicemails, and emails you already have on personal accounts",
                "Write down the reason you were given and who gave it, on the day it happened",
            ]),
        ],
        "expect": [
            ("A chronology review", "The order of reports, responses, and adverse actions is often central to how a workplace matter is evaluated."),
            ("A documents and access check", "What you have, what you can still request, and what is already gone is mapped early."),
            ("A procedure and timing screen", "Whether an administrative step may apply, and what dates are already running, is reviewed with your notices."),
            ("A next-step decision", "The firm may accept, refer, co-counsel, or decline after conflicts and fit review. No outcome is promised."),
        ],
        "preserve": [
            "Your own dated log, kept on a personal device or account",
            "Separation, severance, and final pay documents, including unsigned versions",
            "Pay stubs, schedules, reviews, and any written discipline",
            "Written reports you made and any response you received",
        ],
        "faqs": [
            ("Can I copy my work emails before I leave?", "Employer systems and policies control company material, and taking confidential company information can create separate problems. Focus on your own employment records, keep personal notes on personal accounts, and ask about the personnel file process."),
            ("Should I report internally first?", "Whether and how to report is a decision with consequences that depend on your situation, and no web page can make it for you. What helps in every version is a dated record of what happened and what you were told."),
            ("How long should I keep documenting?", "Through the end of the employment relationship and beyond, including how the employer responds afterward. The period after a report is often the most important part of the timeline."),
        ],
        "related": [
            ("Employment and workplace claims review", "/practice-areas/employment-workplace-claims/"),
            ("Deadlines and early case review", "/resources/deadlines-and-early-review/"),
            ("What to prepare before a case review", "/resources/prepare-for-case-review/"),
        ],
    },
]

RESOURCE_ROUTES = [f'/resources/{guide["slug"]}/' for guide in RESOURCE_GUIDES]

ROUTES = [
    "/", "/attorney-tam-berhe/", "/case-review-process/", "/free-case-review/",
    "/living-trust/", "/referrals-co-counsel/",
    "/landing/truck-fleet-rideshare-accident-california/",
    "/landing/garden-grove-chemical-leak/", "/practice-areas/",
    *[f'/practice-areas/{practice["slug"]}/' for practice in PRACTICES],
    "/resources/", *RESOURCE_ROUTES,
    "/privacy.html", "/terms.html", "/disclaimer.html",
]

GARDEN_SOURCES = [
    ("City of Garden Grove hazardous-materials incident page", "https://ggcity.org/emergency"),
    ("Orange County official Garden Grove chemical spill incident page", "https://www.ocgov.com/page/garden-grove-chemical-spill-incident"),
    ("Office of the Governor of California", "https://www.gov.ca.gov/2026/05/23/governor-newsom-proclaims-state-of-emergency-in-orange-county-in-response-to-ongoing-chemical-incident-in-garden-grove-makes-additional-shelter-sites-available/"),
    ("California Office of Emergency Services (Cal OES)", "https://www.news.caloes.ca.gov/community-resources-for-garden-grove-hazmat-incident/"),
    ("CDC/NIOSH methyl methacrylate guide", "https://www.cdc.gov/niosh/npg/npgd0426.html"),
    ("Orange County Department of Education", "https://newsroom.ocde.us/several-garden-grove-unified-campuses-closed-following-chemical-leak-response/"),
    ("ABC7 Los Angeles", "https://abc7.com/live-updates/garden-grove-chemical-tank-emergency-leaking-toxic-chemicals-orange-county-will-spill-explode-officials-say/19152918/"),
    ("CalMatters", "https://calmatters.org/environment/2026/05/gkn-aerospace-chemical-leak-california/"),
    ("ABC7 / EPA compliance reporting", "https://abc7.com/post/check-enforcement-compliance-history-chemical-facilities-area-epas-interactive-map/19176249/"),
    ("NBC Los Angeles", "https://www.nbclosangeles.com/news/local/garden-grove-chemical-tank-blast-map/3894254/"),
    ("CBS Los Angeles", "https://www.cbsnews.com/losangeles/news/garden-grove-gkn-aerospace-chemical-leak-investigation-orange-county-district-attorney-whistleblowers/"),
    ("Orange County Register: cooling-system briefing", "https://www.ocregister.com/2026/05/26/chemical-tank-in-garden-grove-at-92-degrees-tuesday-a-m-crews-work-to-lower-it/"),
    ("Orange County Register: early lawsuit reporting", "https://www.ocregister.com/2026/05/26/70-people-suing-garden-grove-chemical-tank-owner-over-crisis-as-of-tuesday/"),
    ("PacerMonitor: Page docket reference", "https://www.pacermonitor.com/public/case/64832097/Page_et_al_v_GKN_AEROSPACE_TRANSPARENCY_SYSTEMS_INC_et_al"),
    ("PacerMonitor: Sanchez docket reference", "https://www.pacermonitor.com/public/case/64838071/Sanchez_v_GKN_AEROSPACE_TRANSPARENCY_SYSTEMS_INC_et_al"),
    ("Daily Journal", "https://www.dailyjournal.com/article/391685-garden-grove-chemical-emergency-spurs-new-plaintiffs-legal-coalition"),
    ("KFI AM 640", "https://kfiam640.iheart.com/content/2026-05-26-lawsuit-filed-against-gkn-aerospace-over-chemical-leak/"),
    ("South Coast AQMD", "https://www.aqmd.gov/home/air-quality/complaints"),
    ("GKN Garden Grove Class Action site", "https://www.gkngardengrove.com/"),
]
